
 

export const GET_SAVED_QUOTES_REQUEST = "GET_SAVED_QUOTES_REQUEST";
export const GET_SAVED_QUOTES_SUCCESS = "GET_SAVED_QUOTES_SUCCESS";
export const GET_SAVED_QUOTES_FAILURE = "GET_SAVED_QUOTES_FAILURE"