
 

export const GET_SAVED_QUOTES_REQUEST = "GET_SAVED_QUOTES_REQUEST";
export const GET_SAVED_QUOTES_SUCCESS = "GET_SAVED_QUOTES_SUCCESS";
export const GET_SAVED_QUOTES_FAILURE = "GET_SAVED_QUOTES_FAILURE"

export const GET_RANDOM_QUOTES_REQUEST = "GET_RANDOM_QUOTES_REQUEST";
export const GET_RANDOM_QUOTES_SUCCESS = "GET_RANDOM_QUOTES_SUCCESS";
export const GET_RANDOM_QUOTES_FAILURE = "GET_RANDOM_QUOTES_FAILURE"


export const LOADING_STARTED = "LOADING_STARTED"
export const LOADING_COMPLETED ="LOADING_COMPLETED"
