


export const GET_RANDOM_QUOTES_REQUEST = "GET_RANDOM_QUOTES_REQUEST";
export const GET_RANDOM_QUOTES_SUCCESS = "GET_RANDOM_QUOTES_SUCCESS";
export const GET_RANDOM_QUOTES_FAILURE = "GET_RANDOM_QUOTES_FAILURE"


export const BOOKMARK='BOOKMARK'
export const UNBOOKMARK='UNBOOKMARK'

